version: '3'
services:

  postgis:
    image: kartoza/postgis
    ports:
    - "55432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
      POSTGRES_DBNAME: qgisfeed
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      internal:

  qgisfeed:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      QGIS_FEED_PRDUCTION: true
    command: /code/entrypoint.sh
    ports:
    - "80:8000"
    volumes:
      - ${QGISFEED_DOCKER_SHARED_VOLUME}:/shared-volume
    depends_on:
      - postgis
     logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      internal:

  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ${QGISFEED_DOCKER_SHARED_VOLUME}:/shared-volume
      - ./config/nginx:/etc/nginx/conf.d
    networks:
      internal:


volumes:
    shared-volume:

networks:
    internal:


