version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up -d
      - run: sleep 20  # Wait for postgresql
      - run: docker-compose exec qgisfeed sh -c "cd /code/qgisfeedproject && python manage.py test qgisfeed"
